Inspec/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^inspector/', include('main.urls', namespace='main', app_name='main')),
]

main/urls.py
from django.conf.urls import url
from .views import *



urlpatterns=[
    #url(r'^projectnew/$', views.create_projec,),
    #url(r'^projectview/$', views.list_project,),
    #url(r'^projectdetail/(?P<idp>[0-9]+)/$', views.detail_project, ),
    url(r'^$', ProjectIndex.as_view(), name='project_index'),
    url(r'^project_index$', ProjectIndex.as_view(), name='project_index'),
    url(r'^project_add$', ProjectAdd.as_view(), name="project_add"),
    url(r'^(?P<pk>\d+)/project_view/$', ProjectView.as_view(), name="project_view"),
    url(r'^(?P<pk>\d+)/project_edit/$', ProjectEdit.as_view(), name="project_edit"),
    url(r'^(?P<pk>\d+)/project_delete/$', ProjectDelete.as_view(), name="project_delete"),
]

main/models.py
from django.db import models

# Create your models here.

Type_of_user=(('Testing','Testing'),
                  ('Administrator','Administrator'))

Status_of_projects=(('Active','Active'),
                    ('inactive','inactive'),
                                       )

class User(models.Model):
    id=models.AutoField(primary_key=True, null=False, unique=True)
    name=models.CharField(null=False,max_length=50)
    last_name=models.CharField(null=False,max_length=50)
    nickname=models.CharField(null=False,max_length=50)
    status=models.BooleanField(null=False, default=False)
    type=models.CharField(choices=Type_of_user, null=False, max_length=50)

    def __str__(self):
        return '%s'% (self.nickname)
    def __getnamec__(self):
        return '%s %s' %(self.name,self.last_name)



class FilesOfp(models.Model):
    file=models.CharField(max_length=300)
    def __str__(self):
        return '%s-%s'% (self.id,self.file)







class Project(models.Model):
    idp=models.AutoField(primary_key=True, null=False, unique=True)
    name=models.CharField(null=False, max_length=120)
    URL=models.URLField(null=False)
    creation_date=models.DateField(auto_now_add=True)
    status=models.CharField(null=False,max_length=60, choices=Status_of_projects)
    fle=models.ManyToManyField(FilesOfp)
    id=models.ForeignKey(User)


    def __str__(self):
        return '%s   -     %s    -    %s    -    %s' % (self.name, self.creation_date,self.status,self.id)











class Rulez(models.Model):
    idre=models.AutoField(primary_key=True, null=False, unique=True)
    Typer=models.CharField(null=False, max_length=150)
    description=models.CharField(null=False, max_length=300)
    codigo=models.CharField(null=False, max_length=40)

main/views.py
from datetime import timezone

from django.shortcuts import render, render_to_response, redirect
from main.models import *
from main.form import *
from django.http import Http404
import requests
from django.views.generic import View
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

# Create your views here.

class ProjectIndex(View):

    template_name='index.html'


    def get(self,request, *args, **kwargs):
        projects=Project.objects.filter(status='Active')
        return render(request, self.template_name, {'projects':projects,})
        print(projects)


class ProjectAdd(View):
    template_name='add.html'

    def get(self, request, *args, **kwargs):
        form = ProjectForm()
        return render(request, self.template_name, {
                    'form': form,
                            })

    def post(self, request, *args, **kwargs):
        form = ProjectForm(request.POST)
        if form.is_valid():
            projects = form.save()
            return HttpResponseRedirect(reverse('main:project_index'))
        else:
            return render(request, self.template_name, {'form': form})

class ProjectEdit(View):
    template_name = "edit.html"

    def get(self, request, *args, **kwargs):
            project = Project.objects.get(pk=kwargs['pk'])
            form = ProjectForm(instance=project)
            return render(request, self.template_name, {
            'form': form,
            })
    def post(self, request, *args, **kwargs):
            project = Project.objects.get(pk=kwargs['pk'])
            form = ProjectForm(request.POST, instance=project)
            if form.is_valid():
                project = form.save()
                return HttpResponseRedirect(reverse('main:project_index'))
            else:
                return render(request, self.template_name, {'form': form, })


class ProjectView(View):
    template_name='view.html'
#aquí mostrar el repositorio

    def get(self,request, *args, **kwargs):
        project=Project.objects.get(pk=kwargs['pk'])
        return render(request, self.template_name, {'project': project})


class ProjectDelete(View):
   def get(self, request, *args, **kwargs):
        account = Project.objects.get(pk=kwargs['pk'])
        account.deleted = True
        account.save()
        return HttpResponseRedirect(reverse('inspector:project_index'))

main/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Inspector de código</title>
</head>
<body>
{% block headline %}
<div class="header">
<h1>Inspector de código</h1>

<a href="admin/project/index.html">Inicio</a>
<a href="/main/templates/inspector/index.html">Inspector</a>
<a href="/main/templates/reportes/index.html">Reportes</a>
<a href="/main/templates/admin/index.html">Administración</a>
<a href="cerrar_sesion.html">Cerrar Sesión</a>
</div>
{%  endblock %}

    {% block content %}
        <div class="content container">

        </div>
    {% endblock %}




</body>
</html>

main/templates/cerrar_sesion.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

main/templates/inspector/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

main/templates/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Inspector</title>
</head>
<body style="padding: 20px;">
<h1>Inspector de Código</h1>
<hr/>
{% block content %}

{% endblock %}
</body>
</html>

main/templates/project/add.html
{% extends "/root/PycharmProjects/Inspec/main/templates/master.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="{% url 'main:project_index' %}">Volver</a><br /><br />
<form action="{% url 'main:project_add' %}" method="post">
{% csrf_token %}
{% for field in form %}
<div>
<label>{{ field.label }}</label>
{{ field }}
<div>{{ field.errors }}</div>
</div>
{% endfor %}
<input type="submit" value="Guardar" />
'<tr><th>Name:</th><td><input maxlength="120" name="name" type="text" /></td></tr>\n<tr><th>URL:</th><td><input maxlength="200" name="URL" type="url" /></td></tr>\n<tr><th>Status:</th><td><select name="status">\n<option value="" selected="selected">---------</option>\n<option value="Active">Active</option>\n<option value="inactive">inactive</option>\n</select></td></tr>\n<tr><th>Id:</th><td><select name="id">\n<option value="" selected="selected">---------</option>\n<option value="1">pitalveiro</option>\n<option value="2">Avasquez</option>\n<option value="3">Amarin</option>\n</select></td></tr>\n<tr><th>Fle:</th><td><ul><li><label><input name="fle" type="checkbox" value="1" /> index.php</label></li><li><label><input name="fle" type="checkbox" value="2" /> others.php</label></li><li><label><input name="fle" type="checkbox" value="3" /> people.php</label></li></ul></td></tr>'
</form>
</body>
</html>
{% endblock %}

main/templates/project/edit.html
{% extends "/root/PycharmProjects/Inspec/main/templates/master.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="{% url 'main:project_index' %}">Volver</a><br /><br />
<form action="{% url 'main:project_edit' form.instance.idp %}" method="post">
{% csrf_token %}
{% for field in form %}
<div>
<label>{{ field.label }}</label>
{{ field }}
<div>{{ field.errors }}</div>
</div>
{% endfor %}
<input type="submit" value="Guardar" />
</form>
</body>
</html>
{% endblock %}

main/templates/project/index.html
{% extends "/root/PycharmProjects/Inspec/main/templates/master.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Proyectos</h2>
{% for project in projects %}

 {{ project }}

 [<a href="{% url 'main:project_add' %}">Agregar</a>]<br/><br/>
<div>

<a href="{% url 'main:project_view' project.idp %}">Ver</a> |
<a href="{% url 'main:project_edit' project.idp %}">Editar</a> |
<a href="{% url 'main:project_delete' project.idp %}">Eliminar</a>

{% endfor %}
<script type="text/javascript">
function delete_projec(url) {
if(confirm('Seguro eliminar esta proyecto ?')) {
window.location = url;
}
}
</script>
</div>
</body>
</html>
{% endblock %}

main/templates/project/view.html
{% extends "/root/PycharmProjects/Inspec/main/templates/master.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="{% url 'main:project_index' %}">Volver</a><br /><br />
<b>Tipo documento:</b> {{ project.id }}<br />
<!-- get_document_type_display -->
<b>Documento:</b> {{ project.idp }}<br />
<b>Nombre:</b> {{ account.full_name }}<br />
<b>Fecha creación:</b> {{ account.created_at|date:"Y-m-d H:i:s" }}<br />
</body>
</html>
{% endblock %}

main/templates/reportes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/index.html
{% extends "/root/PycharmProjects/Inspec/main/templates/master.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Proyectos</h2>
{% for project in projects %}
[ <a href="{% url 'inspector:project_add' %}">Agregar</a>]<br/><br/>
<div>
[
<a href="{% url 'inspector:project_view' project.id %}">Ver</a> |
<a href="{% url 'inspector:project_edit' project.id %}">Editar</a> |
<a href="{% url 'inspector:project_delete' project.id %}">Eliminar</a>
] {{ project }}




</div>

<div>{{ project }}</div>
{% endfor %}
<script type="text/javascript">
function delete_projec(url) {
if(confirm('Seguro eliminar esta proyecto ?')) {
window.location = url;
}
}
</script>
</body>
</html>
{% endblock %}